sidebar:
  logo:
    title: '[<img no-lazy height="32px" src=""/>](/)'
  menu:
    post: '[首页](/)'
    # wiki: '[btn.wiki](/wiki/)'
    # notes: '[笔记](/notes/)'
    # more: '[更多](/more/)'

# Sidebar widgets
widgets:
  # Recent update
  recent:
    layout: recent
    rss: /atom.xml # npm i hexo-generator-feed
    limit: 5 # Count of posts
  # TOC (valid only in layout:post/wiki)
  toc:
    layout: toc
    list_number: true
    min_depth: 3
    max_depth: 5
  # welcome
  welcome:
    layout: markdown
    title: 欢迎光临小站
    content:
      - 本站由简约而精美的 Stellar 主题所构建，希望大家能够喜欢。
      - 本站只用作文档记录，不参与商业活动
      # - 本站可跟随系统自动切换【深色/浅色】模式。

# 评论
comments:
  service: utterances # utterances
  utterances:
    repo: xaoxuu/blog-comments

# article:
#   # npm i hexo-related-popular-posts
#   related_posts:
#     enable: true
#     title: 您可能感兴趣的文章
#     max_count: 5